spring.application.name=vehicule.spat-backend

# ===============================
# Configuration PostgreSQL
# ===============================
spring.datasource.url=${SPAT_DB_URL}
spring.datasource.username=${SPAT_DB_USERNAME}
spring.datasource.password=${SPAT_DB_PASSWORD}

# ===============================
# Hibernate / JPA
# ===============================

# Création / mise à jour automatique des tables
# À conserver uniquement pendant le développement
spring.jpa.hibernate.ddl-auto=update

# Affichage des requêtes SQL
spring.jpa.show-sql=true

# Dialecte PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# JWT Security
# ===============================
jwt.secret=${SPAT_JWT_SECRET}


# ===============================
# Configuration Email
# ===============================
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525

spring.mail.username=${SPAT_MAIL_USERNAME}
spring.mail.password=${SPAT_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# ===============================
# Frontend
# ===============================
app.frontend.url=${SPAT_FRONTEND_URL}