spring.application.name=vehicule.spat-backend


# =========================================================
# POSTGRESQL
# =========================================================

spring.datasource.url=${SPAT_DB_URL}
spring.datasource.username=${SPAT_DB_USERNAME}
spring.datasource.password=${SPAT_DB_PASSWORD}


# =========================================================
# HIBERNATE / JPA
# =========================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false


# =========================================================
# JWT SECURITY
# =========================================================

jwt.secret=${SPAT_JWT_SECRET}


# =========================================================
# EMAIL SMTP - GMAIL
# =========================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=465

spring.mail.username=ingitspat@gmail.com
spring.mail.password=fehf ndlg fzsg ldfv
  #${SPAT_MAIL_PASSWORD}

# Authentification SMTP
spring.mail.properties.mail.smtp.auth=true

# Gmail port 587 = STARTTLS
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false

# Ne pas utiliser SSL implicite avec le port 587
spring.mail.properties.mail.smtp.ssl.enable=true

# Certificat Gmail
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Timeouts
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# Encodage
spring.mail.default-encoding=UTF-8

# Expéditeur visible
app.mail.from=Gestion de parc automobile <ingitspat@gmail.com>


# =========================================================
# FRONTEND
# =========================================================

app.frontend.url=${SPAT_FRONTEND_URL}


# =========================================================
# GPS - GPS-GPS.ONLINE
# =========================================================
# BLOC GPS CONSERVE TEL QU'IL FONCTIONNE ACTUELLEMENT
# NE PAS MODIFIER
# =========================================================

gps.enabled=true

gps.base-url=https://gps-gps.online

gps.items-path=/objects/items

gps.items-json-path=/objects/items_json

gps.cookie=${SPAT_GPS_COOKIE:}

gps.xsrf-token=${SPAT_GPS_XSRF_TOKEN:}

gps.refresh-ms=5000

gps.initial-delay-ms=5000

gps.identifier=${SPAT_GPS_IDENTIFIER}
gps.password=${SPAT_GPS_PASSWORD}